# Handling Missing Data

In [2]:
import pandas as pd
import numpy as np

In [44]:
df = pd.read_csv("mtcars.csv")
df

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [4]:
fr = [i for i in df.columns if df[i].isnull().sum() > 1]
print(len(fr))

0

In [5]:
# Replacing 0's with NAN
df = df.replace(['0', 0], np.nan)
df

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6.0,160.0,110.0,3.90,2.620,16.46,NaN,1.0,4.0,4.0
1,Mazda RX4 Wag,21.0,6.0,160.0,110.0,3.90,2.875,17.02,NaN,1.0,4.0,4.0
2,Datsun 710,22.8,4.0,108.0,93.0,3.85,2.320,18.61,1.0,1.0,4.0,1.0
3,Hornet 4 Drive,21.4,6.0,258.0,110.0,3.08,3.215,19.44,1.0,NaN,3.0,1.0
4,Hornet Sportabout,18.7,8.0,360.0,175.0,3.15,3.440,17.02,NaN,NaN,3.0,2.0
5,Valiant,18.1,6.0,225.0,105.0,2.76,3.460,20.22,1.0,NaN,3.0,1.0
6,Duster 360,14.3,8.0,360.0,245.0,3.21,3.570,15.84,NaN,NaN,3.0,4.0
7,Merc 240D,24.4,4.0,146.7,62.0,3.69,3.190,20.00,1.0,NaN,4.0,2.0
8,Merc 230,22.8,4.0,140.8,95.0,3.92,3.150,22.90,1.0,NaN,4.0,2.0
9,Merc 280,19.2,6.0,167.6,123.0,3.92,3.440,18.30,1.0,NaN,4.0,4.0
10,Merc 280C,17.8,6.0,167.6,123.0,3.92,3.440,18.90,1.0,NaN,4.0,4.0
11,Merc 450SE,16.4,8.0,275.8,180.0,3.07,4.070,17.40,NaN,NaN,3.0,3.0
12,Merc 450SL,17.3,8.0,275.8,180.0,3.07,3.730,17.60,NaN,NaN,3.0,3.0
13,Merc 450SLC,15.2,8.0,275.8,180.0,3.07,3.780,18.00,NaN,NaN,3.0,3.0
14,Cadillac Fleetwood,10.4,8.0,472.0,205.0,2.93,5.250,17.98,NaN,NaN,3.0,4.0
15,Lincoln Continental,10.4,8.0,460.0,215.0,3.00,5.424,17.82,NaN,NaN,3.0,4.0
16,Chrysler Imperial,14.7,8.0,440.0,230.0,3.23,5.345,17.42,NaN,NaN,3.0,4.0
17,Fiat 128,32.4,4.0,78.7,66.0,4.08,2.200,19.47,1.0,1.0,4.0,1.0
18,Honda Civic,30.4,4.0,75.7,52.0,4.93,1.615,18.52,1.0,1.0,4.0,2.0
19,Toyota Corolla,33.9,4.0,71.1,65.0,4.22,1.835,19.90,1.0,1.0,4.0,1.0
20,Toyota Corona,21.5,4.0,120.1,97.0,3.70,2.465,20.01,1.0,NaN,3.0,1.0
21,Dodge Challenger,15.5,8.0,318.0,150.0,2.76,3.520,16.87,NaN,NaN,3.0,2.0
22,AMC Javelin,15.2,8.0,304.0,150.0,3.15,3.435,17.30,NaN,NaN,3.0,2.0
23,Camaro Z28,13.3,8.0,350.0,245.0,3.73,3.840,15.41,NaN,NaN,3.0,4.0
24,Pontiac Firebird,19.2,8.0,400.0,175.0,3.08,3.845,17.05,NaN,NaN,3.0,2.0
25,Fiat X1-9,27.3,4.0,79.0,66.0,4.08,1.935,18.90,1.0,1.0,4.0,1.0
26,Porsche 914-2,26.0,4.0,120.3,91.0,4.43,2.140,16.70,NaN,1.0,5.0,2.0
27,Lotus Europa,30.4,4.0,95.1,113.0,3.77,1.513,16.90,1.0,1.0,5.0,2.0
28,Ford Pantera L,15.8,8.0,351.0,264.0,4.22,3.170,14.50,NaN,1.0,5.0,4.0
29,Ferrari Dino,19.7,6.0,145.0,175.0,3.62,2.770,15.50,NaN,1.0,5.0,6.0
30,Maserati Bora,15.0,8.0,301.0,335.0,3.54,3.570,14.60,NaN,1.0,5.0,8.0
31,Volvo 142E,21.4,4.0,121.0,109.0,4.11,2.780,18.60,1.0,1.0,4.0,2.0

In [6]:
fr = [i for i in df.columns if df[i].isnull().sum() > 1]
print("No.of missing values:",len(fr))
fr

No.of missing values: 2

['vs', 'am']

In [7]:
for i in fr:
    print(i,":",np.round(df[i].isnull().mean(),2))

vs : 0.56
am : 0.59

In [8]:
# percentage of missing values in each column
for i in fr:
    print(i,":",np.round(df[i].isnull().mean()*100,2),"%")

vs : 56.25 %
am : 59.38 %

In [9]:
df.shape

(32, 12)

In [10]:
df.describe()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,14.0,13.0,32.000000,32.0000
mean,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.848750,1.0,1.0,3.687500,2.8125
std,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.786943,0.0,0.0,0.737804,1.6152
min,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,1.0,1.0,3.000000,1.0000
25%,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.892500,1.0,1.0,3.000000,2.0000
50%,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.710000,1.0,1.0,4.000000,2.0000
75%,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.0,1.0,4.000000,4.0000
max,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.0,1.0,5.000000,8.0000

In [11]:
df.info() #Summary of dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   model   32 non-null     object
 1   mpg     32 non-null     float64
 2   cyl     32 non-null     float64
 3   disp    32 non-null     float64
 4   hp      32 non-null     float64
 5   drat    32 non-null     float64
 6   wt      32 non-null     float64
 7   qsec    32 non-null     float64
 8   vs      14 non-null     float64
 9   am      13 non-null     float64
 10  gear    32 non-null     float64
 11  carb    32 non-null     float64
dtypes: float64(11), object(1)
memory usage: 3.1+ KB

# Filling Method1

In [12]:
#Filling with zeros
df1 = pd.read_csv('mtcars.csv')
df1.fillna(0)
print(df1) #Dataset with zeros
print(df) #Dataset with nulls
# Now there are no missing values

                  model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1

    gear  carb
0      4     4
1      4     4
2      4     1
3      3     1
4      3     2
5      3     1
6      3     4
7      4     2
8      4     2
9      4     4
10     4     4
11     3     3
12     3     3
13     3     3
14     3     4
15     3     4
16     3     4
17     4     1
18     4     2
19     4     1
20     3     1
21     3     2
22     3     2
23     3     4
24     3     2
25     4     1
26     5     2
27     5     2
28     5     4
29     5     6
30     5     8
31     4     2
                  model   mpg  cyl   disp     hp  drat     wt   qsec   vs  \
0             Mazda RX4  21.0  6.0  160.0  110.0  3.90  2.620  16.46  NaN
1         Mazda RX4 Wag  21.0  6.0  160.0  110.0  3.90  2.875  17.02  NaN
2            Datsun 710  22.8  4.0  108.0   93.0  3.85  2.320  18.61  1.0
3        Hornet 4 Drive  21.4  6.0  258.0  110.0  3.08  3.215  19.44  1.0
4     Hornet Sportabout  18.7  8.0  360.0  175.0  3.15  3.440  17.02  NaN
5               Valiant  18.1  6.0  225.0  105.0  2.76  3.460  20.22  1.0
6            Duster 360  14.3  8.0  360.0  245.0  3.21  3.570  15.84  NaN
7             Merc 240D  24.4  4.0  146.7   62.0  3.69  3.190  20.00  1.0
8              Merc 230  22.8  4.0  140.8   95.0  3.92  3.150  22.90  1.0
9              Merc 280  19.2  6.0  167.6  123.0  3.92  3.440  18.30  1.0
10            Merc 280C  17.8  6.0  167.6  123.0  3.92  3.440  18.90  1.0
11           Merc 450SE  16.4  8.0  275.8  180.0  3.07  4.070  17.40  NaN
12           Merc 450SL  17.3  8.0  275.8  180.0  3.07  3.730  17.60  NaN
13          Merc 450SLC  15.2  8.0  275.8  180.0  3.07  3.780  18.00  NaN
14   Cadillac Fleetwood  10.4  8.0  472.0  205.0  2.93  5.250  17.98  NaN
15  Lincoln Continental  10.4  8.0  460.0  215.0  3.00  5.424  17.82  NaN
16    Chrysler Imperial  14.7  8.0  440.0  230.0  3.23  5.345  17.42  NaN
17             Fiat 128  32.4  4.0   78.7   66.0  4.08  2.200  19.47  1.0
18          Honda Civic  30.4  4.0   75.7   52.0  4.93  1.615  18.52  1.0
19       Toyota Corolla  33.9  4.0   71.1   65.0  4.22  1.835  19.90  1.0
20        Toyota Corona  21.5  4.0  120.1   97.0  3.70  2.465  20.01  1.0
21     Dodge Challenger  15.5  8.0  318.0  150.0  2.76  3.520  16.87  NaN
22          AMC Javelin  15.2  8.0  304.0  150.0  3.15  3.435  17.30  NaN
23           Camaro Z28  13.3  8.0  350.0  245.0  3.73  3.840  15.41  NaN
24     Pontiac Firebird  19.2  8.0  400.0  175.0  3.08  3.845  17.05  NaN
25            Fiat X1-9  27.3  4.0   79.0   66.0  4.08  1.935  18.90  1.0
26        Porsche 914-2  26.0  4.0  120.3   91.0  4.43  2.140  16.70  NaN
27         Lotus Europa  30.4  4.0   95.1  113.0  3.77  1.513  16.90  1.0
28       Ford Pantera L  15.8  8.0  351.0  264.0  4.22  3.170  14.50  NaN
29         Ferrari Dino  19.7  6.0  145.0  175.0  3.62  2.770  15.50  NaN
30        Maserati Bora  15.0  8.0  301.0  335.0  3.54  3.570  14.60  NaN
31           Volvo 142E  21.4  4.0  121.0  109.0  4.11  2.780  18.60  1.0

     am  gear  carb
0   1.0   4.0   4.0
1   1.0   4.0   4.0
2   1.0   4.0   1.0
3   NaN   3.0   1.0
4   NaN   3.0   2.0
5   NaN   3.0   1.0
6   NaN   3.0   4.0
7   NaN   4.0   2.0
8   NaN   4.0   2.0
9   NaN   4.0   4.0
10  NaN   4.0   4.0
11  NaN   3.0   3.0
12  NaN   3.0   3.0
13  NaN   3.0   3.0
14  NaN   3.0   4.0
15  NaN   3.0   4.0
16  NaN   3.0   4.0
17  1.0   4.0   1.0
18  1.0   4.0   2.0
19  1.0   4.0   1.0
20  NaN   3.0   1.0
21  NaN   3.0   2.0
22  NaN   3.0   2.0
23  NaN   3.0   4.0
24  NaN   3.0   2.0
25  1.0   4.0   1.0
26  1.0   5.0   2.0
27  1.0   5.0   2.0
28  1.0   5.0   4.0
29  1.0   5.0   6.0
30  1.0   5.0   8.0
31  1.0   4.0   2.0

# Filling Method2

In [13]:
#filling with before values in terms of columns
df2 = df.fillna(method='ffill', axis=1)#copied from before column(left)
print(df2)
df2 = df.fillna(method='ffill', axis=0)#copied from before row(above)
print(df2)

                  model   mpg  cyl   disp     hp  drat     wt   qsec     vs  \
0             Mazda RX4  21.0  6.0  160.0  110.0   3.9   2.62  16.46  16.46
1         Mazda RX4 Wag  21.0  6.0  160.0  110.0   3.9  2.875  17.02  17.02
2            Datsun 710  22.8  4.0  108.0   93.0  3.85   2.32  18.61    1.0
3        Hornet 4 Drive  21.4  6.0  258.0  110.0  3.08  3.215  19.44    1.0
4     Hornet Sportabout  18.7  8.0  360.0  175.0  3.15   3.44  17.02  17.02
5               Valiant  18.1  6.0  225.0  105.0  2.76   3.46  20.22    1.0
6            Duster 360  14.3  8.0  360.0  245.0  3.21   3.57  15.84  15.84
7             Merc 240D  24.4  4.0  146.7   62.0  3.69   3.19   20.0    1.0
8              Merc 230  22.8  4.0  140.8   95.0  3.92   3.15   22.9    1.0
9              Merc 280  19.2  6.0  167.6  123.0  3.92   3.44   18.3    1.0
10            Merc 280C  17.8  6.0  167.6  123.0  3.92   3.44   18.9    1.0
11           Merc 450SE  16.4  8.0  275.8  180.0  3.07   4.07   17.4   17.4
12           Merc 450SL  17.3  8.0  275.8  180.0  3.07   3.73   17.6   17.6
13          Merc 450SLC  15.2  8.0  275.8  180.0  3.07   3.78   18.0   18.0
14   Cadillac Fleetwood  10.4  8.0  472.0  205.0  2.93   5.25  17.98  17.98
15  Lincoln Continental  10.4  8.0  460.0  215.0   3.0  5.424  17.82  17.82
16    Chrysler Imperial  14.7  8.0  440.0  230.0  3.23  5.345  17.42  17.42
17             Fiat 128  32.4  4.0   78.7   66.0  4.08    2.2  19.47    1.0
18          Honda Civic  30.4  4.0   75.7   52.0  4.93  1.615  18.52    1.0
19       Toyota Corolla  33.9  4.0   71.1   65.0  4.22  1.835   19.9    1.0
20        Toyota Corona  21.5  4.0  120.1   97.0   3.7  2.465  20.01    1.0
21     Dodge Challenger  15.5  8.0  318.0  150.0  2.76   3.52  16.87  16.87
22          AMC Javelin  15.2  8.0  304.0  150.0  3.15  3.435   17.3   17.3
23           Camaro Z28  13.3  8.0  350.0  245.0  3.73   3.84  15.41  15.41
24     Pontiac Firebird  19.2  8.0  400.0  175.0  3.08  3.845  17.05  17.05
25            Fiat X1-9  27.3  4.0   79.0   66.0  4.08  1.935   18.9    1.0
26        Porsche 914-2  26.0  4.0  120.3   91.0  4.43   2.14   16.7   16.7
27         Lotus Europa  30.4  4.0   95.1  113.0  3.77  1.513   16.9    1.0
28       Ford Pantera L  15.8  8.0  351.0  264.0  4.22   3.17   14.5   14.5
29         Ferrari Dino  19.7  6.0  145.0  175.0  3.62   2.77   15.5   15.5
30        Maserati Bora  15.0  8.0  301.0  335.0  3.54   3.57   14.6   14.6
31           Volvo 142E  21.4  4.0  121.0  109.0  4.11   2.78   18.6    1.0

       am gear carb
0     1.0  4.0  4.0
1     1.0  4.0  4.0
2     1.0  4.0  1.0
3     1.0  3.0  1.0
4   17.02  3.0  2.0
5     1.0  3.0  1.0
6   15.84  3.0  4.0
7     1.0  4.0  2.0
8     1.0  4.0  2.0
9     1.0  4.0  4.0
10    1.0  4.0  4.0
11   17.4  3.0  3.0
12   17.6  3.0  3.0
13   18.0  3.0  3.0
14  17.98  3.0  4.0
15  17.82  3.0  4.0
16  17.42  3.0  4.0
17    1.0  4.0  1.0
18    1.0  4.0  2.0
19    1.0  4.0  1.0
20    1.0  3.0  1.0
21  16.87  3.0  2.0
22   17.3  3.0  2.0
23  15.41  3.0  4.0
24  17.05  3.0  2.0
25    1.0  4.0  1.0
26    1.0  5.0  2.0
27    1.0  5.0  2.0
28    1.0  5.0  4.0
29    1.0  5.0  6.0
30    1.0  5.0  8.0
31    1.0  4.0  2.0
                  model   mpg  cyl   disp     hp  drat     wt   qsec   vs  \
0             Mazda RX4  21.0  6.0  160.0  110.0  3.90  2.620  16.46  NaN
1         Mazda RX4 Wag  21.0  6.0  160.0  110.0  3.90  2.875  17.02  NaN
2            Datsun 710  22.8  4.0  108.0   93.0  3.85  2.320  18.61  1.0
3        Hornet 4 Drive  21.4  6.0  258.0  110.0  3.08  3.215  19.44  1.0
4     Hornet Sportabout  18.7  8.0  360.0  175.0  3.15  3.440  17.02  1.0
5               Valiant  18.1  6.0  225.0  105.0  2.76  3.460  20.22  1.0
6            Duster 360  14.3  8.0  360.0  245.0  3.21  3.570  15.84  1.0
7             Merc 240D  24.4  4.0  146.7   62.0  3.69  3.190  20.00  1.0
8              Merc 230  22.8  4.0  140.8   95.0  3.92  3.150  22.90  1.0
9              Merc 280  19.2  6.0  167.6  123.0  3.92  3.440  18.30  1.0
10            Merc 280C  17.8  6.0  167.6  123.0  3.92  3.440  18.90  1.0
11           Merc 450SE  16.4  8.0  275.8  180.0  3.07  4.070  17.40  1.0
12           Merc 450SL  17.3  8.0  275.8  180.0  3.07  3.730  17.60  1.0
13          Merc 450SLC  15.2  8.0  275.8  180.0  3.07  3.780  18.00  1.0
14   Cadillac Fleetwood  10.4  8.0  472.0  205.0  2.93  5.250  17.98  1.0
15  Lincoln Continental  10.4  8.0  460.0  215.0  3.00  5.424  17.82  1.0
16    Chrysler Imperial  14.7  8.0  440.0  230.0  3.23  5.345  17.42  1.0
17             Fiat 128  32.4  4.0   78.7   66.0  4.08  2.200  19.47  1.0
18          Honda Civic  30.4  4.0   75.7   52.0  4.93  1.615  18.52  1.0
19       Toyota Corolla  33.9  4.0   71.1   65.0  4.22  1.835  19.90  1.0
20        Toyota Corona  21.5  4.0  120.1   97.0  3.70  2.465  20.01  1.0
21     Dodge Challenger  15.5  8.0  318.0  150.0  2.76  3.520  16.87  1.0
22          AMC Javelin  15.2  8.0  304.0  150.0  3.15  3.435  17.30  1.0
23           Camaro Z28  13.3  8.0  350.0  245.0  3.73  3.840  15.41  1.0
24     Pontiac Firebird  19.2  8.0  400.0  175.0  3.08  3.845  17.05  1.0
25            Fiat X1-9  27.3  4.0   79.0   66.0  4.08  1.935  18.90  1.0
26        Porsche 914-2  26.0  4.0  120.3   91.0  4.43  2.140  16.70  1.0
27         Lotus Europa  30.4  4.0   95.1  113.0  3.77  1.513  16.90  1.0
28       Ford Pantera L  15.8  8.0  351.0  264.0  4.22  3.170  14.50  1.0
29         Ferrari Dino  19.7  6.0  145.0  175.0  3.62  2.770  15.50  1.0
30        Maserati Bora  15.0  8.0  301.0  335.0  3.54  3.570  14.60  1.0
31           Volvo 142E  21.4  4.0  121.0  109.0  4.11  2.780  18.60  1.0

     am  gear  carb
0   1.0   4.0   4.0
1   1.0   4.0   4.0
2   1.0   4.0   1.0
3   1.0   3.0   1.0
4   1.0   3.0   2.0
5   1.0   3.0   1.0
6   1.0   3.0   4.0
7   1.0   4.0   2.0
8   1.0   4.0   2.0
9   1.0   4.0   4.0
10  1.0   4.0   4.0
11  1.0   3.0   3.0
12  1.0   3.0   3.0
13  1.0   3.0   3.0
14  1.0   3.0   4.0
15  1.0   3.0   4.0
16  1.0   3.0   4.0
17  1.0   4.0   1.0
18  1.0   4.0   2.0
19  1.0   4.0   1.0
20  1.0   3.0   1.0
21  1.0   3.0   2.0
22  1.0   3.0   2.0
23  1.0   3.0   4.0
24  1.0   3.0   2.0
25  1.0   4.0   1.0
26  1.0   5.0   2.0
27  1.0   5.0   2.0
28  1.0   5.0   4.0
29  1.0   5.0   6.0
30  1.0   5.0   8.0
31  1.0   4.0   2.0

# Filling Method3

In [14]:
#filling with before values in terms of columns
df3 = df.fillna(method='bfill', axis=1)#copied from before column(right)
print(df3)
df3 = df.fillna(method='bfill', axis=0)#copied from before row(down)
print(df3)

                  model   mpg  cyl   disp     hp  drat     wt   qsec   vs  \
0             Mazda RX4  21.0  6.0  160.0  110.0   3.9   2.62  16.46  1.0
1         Mazda RX4 Wag  21.0  6.0  160.0  110.0   3.9  2.875  17.02  1.0
2            Datsun 710  22.8  4.0  108.0   93.0  3.85   2.32  18.61  1.0
3        Hornet 4 Drive  21.4  6.0  258.0  110.0  3.08  3.215  19.44  1.0
4     Hornet Sportabout  18.7  8.0  360.0  175.0  3.15   3.44  17.02  3.0
5               Valiant  18.1  6.0  225.0  105.0  2.76   3.46  20.22  1.0
6            Duster 360  14.3  8.0  360.0  245.0  3.21   3.57  15.84  3.0
7             Merc 240D  24.4  4.0  146.7   62.0  3.69   3.19   20.0  1.0
8              Merc 230  22.8  4.0  140.8   95.0  3.92   3.15   22.9  1.0
9              Merc 280  19.2  6.0  167.6  123.0  3.92   3.44   18.3  1.0
10            Merc 280C  17.8  6.0  167.6  123.0  3.92   3.44   18.9  1.0
11           Merc 450SE  16.4  8.0  275.8  180.0  3.07   4.07   17.4  3.0
12           Merc 450SL  17.3  8.0  275.8  180.0  3.07   3.73   17.6  3.0
13          Merc 450SLC  15.2  8.0  275.8  180.0  3.07   3.78   18.0  3.0
14   Cadillac Fleetwood  10.4  8.0  472.0  205.0  2.93   5.25  17.98  3.0
15  Lincoln Continental  10.4  8.0  460.0  215.0   3.0  5.424  17.82  3.0
16    Chrysler Imperial  14.7  8.0  440.0  230.0  3.23  5.345  17.42  3.0
17             Fiat 128  32.4  4.0   78.7   66.0  4.08    2.2  19.47  1.0
18          Honda Civic  30.4  4.0   75.7   52.0  4.93  1.615  18.52  1.0
19       Toyota Corolla  33.9  4.0   71.1   65.0  4.22  1.835   19.9  1.0
20        Toyota Corona  21.5  4.0  120.1   97.0   3.7  2.465  20.01  1.0
21     Dodge Challenger  15.5  8.0  318.0  150.0  2.76   3.52  16.87  3.0
22          AMC Javelin  15.2  8.0  304.0  150.0  3.15  3.435   17.3  3.0
23           Camaro Z28  13.3  8.0  350.0  245.0  3.73   3.84  15.41  3.0
24     Pontiac Firebird  19.2  8.0  400.0  175.0  3.08  3.845  17.05  3.0
25            Fiat X1-9  27.3  4.0   79.0   66.0  4.08  1.935   18.9  1.0
26        Porsche 914-2  26.0  4.0  120.3   91.0  4.43   2.14   16.7  1.0
27         Lotus Europa  30.4  4.0   95.1  113.0  3.77  1.513   16.9  1.0
28       Ford Pantera L  15.8  8.0  351.0  264.0  4.22   3.17   14.5  1.0
29         Ferrari Dino  19.7  6.0  145.0  175.0  3.62   2.77   15.5  1.0
30        Maserati Bora  15.0  8.0  301.0  335.0  3.54   3.57   14.6  1.0
31           Volvo 142E  21.4  4.0  121.0  109.0  4.11   2.78   18.6  1.0

     am gear carb
0   1.0  4.0  4.0
1   1.0  4.0  4.0
2   1.0  4.0  1.0
3   3.0  3.0  1.0
4   3.0  3.0  2.0
5   3.0  3.0  1.0
6   3.0  3.0  4.0
7   4.0  4.0  2.0
8   4.0  4.0  2.0
9   4.0  4.0  4.0
10  4.0  4.0  4.0
11  3.0  3.0  3.0
12  3.0  3.0  3.0
13  3.0  3.0  3.0
14  3.0  3.0  4.0
15  3.0  3.0  4.0
16  3.0  3.0  4.0
17  1.0  4.0  1.0
18  1.0  4.0  2.0
19  1.0  4.0  1.0
20  3.0  3.0  1.0
21  3.0  3.0  2.0
22  3.0  3.0  2.0
23  3.0  3.0  4.0
24  3.0  3.0  2.0
25  1.0  4.0  1.0
26  1.0  5.0  2.0
27  1.0  5.0  2.0
28  1.0  5.0  4.0
29  1.0  5.0  6.0
30  1.0  5.0  8.0
31  1.0  4.0  2.0
                  model   mpg  cyl   disp     hp  drat     wt   qsec   vs  \
0             Mazda RX4  21.0  6.0  160.0  110.0  3.90  2.620  16.46  1.0
1         Mazda RX4 Wag  21.0  6.0  160.0  110.0  3.90  2.875  17.02  1.0
2            Datsun 710  22.8  4.0  108.0   93.0  3.85  2.320  18.61  1.0
3        Hornet 4 Drive  21.4  6.0  258.0  110.0  3.08  3.215  19.44  1.0
4     Hornet Sportabout  18.7  8.0  360.0  175.0  3.15  3.440  17.02  1.0
5               Valiant  18.1  6.0  225.0  105.0  2.76  3.460  20.22  1.0
6            Duster 360  14.3  8.0  360.0  245.0  3.21  3.570  15.84  1.0
7             Merc 240D  24.4  4.0  146.7   62.0  3.69  3.190  20.00  1.0
8              Merc 230  22.8  4.0  140.8   95.0  3.92  3.150  22.90  1.0
9              Merc 280  19.2  6.0  167.6  123.0  3.92  3.440  18.30  1.0
10            Merc 280C  17.8  6.0  167.6  123.0  3.92  3.440  18.90  1.0
11           Merc 450SE  16.4  8.0  275.8  180.0  3.07  4.070  17.40  1.0
12           Merc 450SL  17.3  8.0  275.8  180.0  3.07  3.730  17.60  1.0
13          Merc 450SLC  15.2  8.0  275.8  180.0  3.07  3.780  18.00  1.0
14   Cadillac Fleetwood  10.4  8.0  472.0  205.0  2.93  5.250  17.98  1.0
15  Lincoln Continental  10.4  8.0  460.0  215.0  3.00  5.424  17.82  1.0
16    Chrysler Imperial  14.7  8.0  440.0  230.0  3.23  5.345  17.42  1.0
17             Fiat 128  32.4  4.0   78.7   66.0  4.08  2.200  19.47  1.0
18          Honda Civic  30.4  4.0   75.7   52.0  4.93  1.615  18.52  1.0
19       Toyota Corolla  33.9  4.0   71.1   65.0  4.22  1.835  19.90  1.0
20        Toyota Corona  21.5  4.0  120.1   97.0  3.70  2.465  20.01  1.0
21     Dodge Challenger  15.5  8.0  318.0  150.0  2.76  3.520  16.87  1.0
22          AMC Javelin  15.2  8.0  304.0  150.0  3.15  3.435  17.30  1.0
23           Camaro Z28  13.3  8.0  350.0  245.0  3.73  3.840  15.41  1.0
24     Pontiac Firebird  19.2  8.0  400.0  175.0  3.08  3.845  17.05  1.0
25            Fiat X1-9  27.3  4.0   79.0   66.0  4.08  1.935  18.90  1.0
26        Porsche 914-2  26.0  4.0  120.3   91.0  4.43  2.140  16.70  1.0
27         Lotus Europa  30.4  4.0   95.1  113.0  3.77  1.513  16.90  1.0
28       Ford Pantera L  15.8  8.0  351.0  264.0  4.22  3.170  14.50  1.0
29         Ferrari Dino  19.7  6.0  145.0  175.0  3.62  2.770  15.50  1.0
30        Maserati Bora  15.0  8.0  301.0  335.0  3.54  3.570  14.60  1.0
31           Volvo 142E  21.4  4.0  121.0  109.0  4.11  2.780  18.60  1.0

     am  gear  carb
0   1.0   4.0   4.0
1   1.0   4.0   4.0
2   1.0   4.0   1.0
3   1.0   3.0   1.0
4   1.0   3.0   2.0
5   1.0   3.0   1.0
6   1.0   3.0   4.0
7   1.0   4.0   2.0
8   1.0   4.0   2.0
9   1.0   4.0   4.0
10  1.0   4.0   4.0
11  1.0   3.0   3.0
12  1.0   3.0   3.0
13  1.0   3.0   3.0
14  1.0   3.0   4.0
15  1.0   3.0   4.0
16  1.0   3.0   4.0
17  1.0   4.0   1.0
18  1.0   4.0   2.0
19  1.0   4.0   1.0
20  1.0   3.0   1.0
21  1.0   3.0   2.0
22  1.0   3.0   2.0
23  1.0   3.0   4.0
24  1.0   3.0   2.0
25  1.0   4.0   1.0
26  1.0   5.0   2.0
27  1.0   5.0   2.0
28  1.0   5.0   4.0
29  1.0   5.0   6.0
30  1.0   5.0   8.0
31  1.0   4.0   2.0

# Filling Method4

In [15]:
#We fill the nulls with mean values
df4 = pd.read_csv('mtcars.csv')
df4 = df4.replace(['0', 0], np.nan)
df4['vs'].fillna(df4['vs'].mean(),inplace=True)
df4['am'].fillna(df4['am'].mean(),inplace=True)
df4

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6.0,160.0,110.0,3.90,2.620,16.46,1.0,1.0,4.0,4.0
1,Mazda RX4 Wag,21.0,6.0,160.0,110.0,3.90,2.875,17.02,1.0,1.0,4.0,4.0
2,Datsun 710,22.8,4.0,108.0,93.0,3.85,2.320,18.61,1.0,1.0,4.0,1.0
3,Hornet 4 Drive,21.4,6.0,258.0,110.0,3.08,3.215,19.44,1.0,1.0,3.0,1.0
4,Hornet Sportabout,18.7,8.0,360.0,175.0,3.15,3.440,17.02,1.0,1.0,3.0,2.0
5,Valiant,18.1,6.0,225.0,105.0,2.76,3.460,20.22,1.0,1.0,3.0,1.0
6,Duster 360,14.3,8.0,360.0,245.0,3.21,3.570,15.84,1.0,1.0,3.0,4.0
7,Merc 240D,24.4,4.0,146.7,62.0,3.69,3.190,20.00,1.0,1.0,4.0,2.0
8,Merc 230,22.8,4.0,140.8,95.0,3.92,3.150,22.90,1.0,1.0,4.0,2.0
9,Merc 280,19.2,6.0,167.6,123.0,3.92,3.440,18.30,1.0,1.0,4.0,4.0
10,Merc 280C,17.8,6.0,167.6,123.0,3.92,3.440,18.90,1.0,1.0,4.0,4.0
11,Merc 450SE,16.4,8.0,275.8,180.0,3.07,4.070,17.40,1.0,1.0,3.0,3.0
12,Merc 450SL,17.3,8.0,275.8,180.0,3.07,3.730,17.60,1.0,1.0,3.0,3.0
13,Merc 450SLC,15.2,8.0,275.8,180.0,3.07,3.780,18.00,1.0,1.0,3.0,3.0
14,Cadillac Fleetwood,10.4,8.0,472.0,205.0,2.93,5.250,17.98,1.0,1.0,3.0,4.0
15,Lincoln Continental,10.4,8.0,460.0,215.0,3.00,5.424,17.82,1.0,1.0,3.0,4.0
16,Chrysler Imperial,14.7,8.0,440.0,230.0,3.23,5.345,17.42,1.0,1.0,3.0,4.0
17,Fiat 128,32.4,4.0,78.7,66.0,4.08,2.200,19.47,1.0,1.0,4.0,1.0
18,Honda Civic,30.4,4.0,75.7,52.0,4.93,1.615,18.52,1.0,1.0,4.0,2.0
19,Toyota Corolla,33.9,4.0,71.1,65.0,4.22,1.835,19.90,1.0,1.0,4.0,1.0
20,Toyota Corona,21.5,4.0,120.1,97.0,3.70,2.465,20.01,1.0,1.0,3.0,1.0
21,Dodge Challenger,15.5,8.0,318.0,150.0,2.76,3.520,16.87,1.0,1.0,3.0,2.0
22,AMC Javelin,15.2,8.0,304.0,150.0,3.15,3.435,17.30,1.0,1.0,3.0,2.0
23,Camaro Z28,13.3,8.0,350.0,245.0,3.73,3.840,15.41,1.0,1.0,3.0,4.0
24,Pontiac Firebird,19.2,8.0,400.0,175.0,3.08,3.845,17.05,1.0,1.0,3.0,2.0
25,Fiat X1-9,27.3,4.0,79.0,66.0,4.08,1.935,18.90,1.0,1.0,4.0,1.0
26,Porsche 914-2,26.0,4.0,120.3,91.0,4.43,2.140,16.70,1.0,1.0,5.0,2.0
27,Lotus Europa,30.4,4.0,95.1,113.0,3.77,1.513,16.90,1.0,1.0,5.0,2.0
28,Ford Pantera L,15.8,8.0,351.0,264.0,4.22,3.170,14.50,1.0,1.0,5.0,4.0
29,Ferrari Dino,19.7,6.0,145.0,175.0,3.62,2.770,15.50,1.0,1.0,5.0,6.0
30,Maserati Bora,15.0,8.0,301.0,335.0,3.54,3.570,14.60,1.0,1.0,5.0,8.0
31,Volvo 142E,21.4,4.0,121.0,109.0,4.11,2.780,18.60,1.0,1.0,4.0,2.0

# Filling Method5

In [16]:
#We fill the nulls with median values
df5 = pd.read_csv('mtcars.csv')
df5 = df4.replace(['0', 0], np.nan)
df5['vs'].fillna(df['vs'].median(),inplace=True)
df5['am'].fillna(df['am'].median(),inplace=True)
df5

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6.0,160.0,110.0,3.90,2.620,16.46,1.0,1.0,4.0,4.0
1,Mazda RX4 Wag,21.0,6.0,160.0,110.0,3.90,2.875,17.02,1.0,1.0,4.0,4.0
2,Datsun 710,22.8,4.0,108.0,93.0,3.85,2.320,18.61,1.0,1.0,4.0,1.0
3,Hornet 4 Drive,21.4,6.0,258.0,110.0,3.08,3.215,19.44,1.0,1.0,3.0,1.0
4,Hornet Sportabout,18.7,8.0,360.0,175.0,3.15,3.440,17.02,1.0,1.0,3.0,2.0
5,Valiant,18.1,6.0,225.0,105.0,2.76,3.460,20.22,1.0,1.0,3.0,1.0
6,Duster 360,14.3,8.0,360.0,245.0,3.21,3.570,15.84,1.0,1.0,3.0,4.0
7,Merc 240D,24.4,4.0,146.7,62.0,3.69,3.190,20.00,1.0,1.0,4.0,2.0
8,Merc 230,22.8,4.0,140.8,95.0,3.92,3.150,22.90,1.0,1.0,4.0,2.0
9,Merc 280,19.2,6.0,167.6,123.0,3.92,3.440,18.30,1.0,1.0,4.0,4.0
10,Merc 280C,17.8,6.0,167.6,123.0,3.92,3.440,18.90,1.0,1.0,4.0,4.0
11,Merc 450SE,16.4,8.0,275.8,180.0,3.07,4.070,17.40,1.0,1.0,3.0,3.0
12,Merc 450SL,17.3,8.0,275.8,180.0,3.07,3.730,17.60,1.0,1.0,3.0,3.0
13,Merc 450SLC,15.2,8.0,275.8,180.0,3.07,3.780,18.00,1.0,1.0,3.0,3.0
14,Cadillac Fleetwood,10.4,8.0,472.0,205.0,2.93,5.250,17.98,1.0,1.0,3.0,4.0
15,Lincoln Continental,10.4,8.0,460.0,215.0,3.00,5.424,17.82,1.0,1.0,3.0,4.0
16,Chrysler Imperial,14.7,8.0,440.0,230.0,3.23,5.345,17.42,1.0,1.0,3.0,4.0
17,Fiat 128,32.4,4.0,78.7,66.0,4.08,2.200,19.47,1.0,1.0,4.0,1.0
18,Honda Civic,30.4,4.0,75.7,52.0,4.93,1.615,18.52,1.0,1.0,4.0,2.0
19,Toyota Corolla,33.9,4.0,71.1,65.0,4.22,1.835,19.90,1.0,1.0,4.0,1.0
20,Toyota Corona,21.5,4.0,120.1,97.0,3.70,2.465,20.01,1.0,1.0,3.0,1.0
21,Dodge Challenger,15.5,8.0,318.0,150.0,2.76,3.520,16.87,1.0,1.0,3.0,2.0
22,AMC Javelin,15.2,8.0,304.0,150.0,3.15,3.435,17.30,1.0,1.0,3.0,2.0
23,Camaro Z28,13.3,8.0,350.0,245.0,3.73,3.840,15.41,1.0,1.0,3.0,4.0
24,Pontiac Firebird,19.2,8.0,400.0,175.0,3.08,3.845,17.05,1.0,1.0,3.0,2.0
25,Fiat X1-9,27.3,4.0,79.0,66.0,4.08,1.935,18.90,1.0,1.0,4.0,1.0
26,Porsche 914-2,26.0,4.0,120.3,91.0,4.43,2.140,16.70,1.0,1.0,5.0,2.0
27,Lotus Europa,30.4,4.0,95.1,113.0,3.77,1.513,16.90,1.0,1.0,5.0,2.0
28,Ford Pantera L,15.8,8.0,351.0,264.0,4.22,3.170,14.50,1.0,1.0,5.0,4.0
29,Ferrari Dino,19.7,6.0,145.0,175.0,3.62,2.770,15.50,1.0,1.0,5.0,6.0
30,Maserati Bora,15.0,8.0,301.0,335.0,3.54,3.570,14.60,1.0,1.0,5.0,8.0
31,Volvo 142E,21.4,4.0,121.0,109.0,4.11,2.780,18.60,1.0,1.0,4.0,2.0

# Filling Method6

In [17]:
#We fill the nulls with mode values
df6 = pd.read_csv('mtcars.csv')
df6 = df4.replace(['0', 0], np.nan)
df6['vs'].fillna(df['vs'].mode(),inplace=True)
df6['am'].fillna(df['am'].mode(),inplace=True)
df6

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6.0,160.0,110.0,3.90,2.620,16.46,1.0,1.0,4.0,4.0
1,Mazda RX4 Wag,21.0,6.0,160.0,110.0,3.90,2.875,17.02,1.0,1.0,4.0,4.0
2,Datsun 710,22.8,4.0,108.0,93.0,3.85,2.320,18.61,1.0,1.0,4.0,1.0
3,Hornet 4 Drive,21.4,6.0,258.0,110.0,3.08,3.215,19.44,1.0,1.0,3.0,1.0
4,Hornet Sportabout,18.7,8.0,360.0,175.0,3.15,3.440,17.02,1.0,1.0,3.0,2.0
5,Valiant,18.1,6.0,225.0,105.0,2.76,3.460,20.22,1.0,1.0,3.0,1.0
6,Duster 360,14.3,8.0,360.0,245.0,3.21,3.570,15.84,1.0,1.0,3.0,4.0
7,Merc 240D,24.4,4.0,146.7,62.0,3.69,3.190,20.00,1.0,1.0,4.0,2.0
8,Merc 230,22.8,4.0,140.8,95.0,3.92,3.150,22.90,1.0,1.0,4.0,2.0
9,Merc 280,19.2,6.0,167.6,123.0,3.92,3.440,18.30,1.0,1.0,4.0,4.0
10,Merc 280C,17.8,6.0,167.6,123.0,3.92,3.440,18.90,1.0,1.0,4.0,4.0
11,Merc 450SE,16.4,8.0,275.8,180.0,3.07,4.070,17.40,1.0,1.0,3.0,3.0
12,Merc 450SL,17.3,8.0,275.8,180.0,3.07,3.730,17.60,1.0,1.0,3.0,3.0
13,Merc 450SLC,15.2,8.0,275.8,180.0,3.07,3.780,18.00,1.0,1.0,3.0,3.0
14,Cadillac Fleetwood,10.4,8.0,472.0,205.0,2.93,5.250,17.98,1.0,1.0,3.0,4.0
15,Lincoln Continental,10.4,8.0,460.0,215.0,3.00,5.424,17.82,1.0,1.0,3.0,4.0
16,Chrysler Imperial,14.7,8.0,440.0,230.0,3.23,5.345,17.42,1.0,1.0,3.0,4.0
17,Fiat 128,32.4,4.0,78.7,66.0,4.08,2.200,19.47,1.0,1.0,4.0,1.0
18,Honda Civic,30.4,4.0,75.7,52.0,4.93,1.615,18.52,1.0,1.0,4.0,2.0
19,Toyota Corolla,33.9,4.0,71.1,65.0,4.22,1.835,19.90,1.0,1.0,4.0,1.0
20,Toyota Corona,21.5,4.0,120.1,97.0,3.70,2.465,20.01,1.0,1.0,3.0,1.0
21,Dodge Challenger,15.5,8.0,318.0,150.0,2.76,3.520,16.87,1.0,1.0,3.0,2.0
22,AMC Javelin,15.2,8.0,304.0,150.0,3.15,3.435,17.30,1.0,1.0,3.0,2.0
23,Camaro Z28,13.3,8.0,350.0,245.0,3.73,3.840,15.41,1.0,1.0,3.0,4.0
24,Pontiac Firebird,19.2,8.0,400.0,175.0,3.08,3.845,17.05,1.0,1.0,3.0,2.0
25,Fiat X1-9,27.3,4.0,79.0,66.0,4.08,1.935,18.90,1.0,1.0,4.0,1.0
26,Porsche 914-2,26.0,4.0,120.3,91.0,4.43,2.140,16.70,1.0,1.0,5.0,2.0
27,Lotus Europa,30.4,4.0,95.1,113.0,3.77,1.513,16.90,1.0,1.0,5.0,2.0
28,Ford Pantera L,15.8,8.0,351.0,264.0,4.22,3.170,14.50,1.0,1.0,5.0,4.0
29,Ferrari Dino,19.7,6.0,145.0,175.0,3.62,2.770,15.50,1.0,1.0,5.0,6.0
30,Maserati Bora,15.0,8.0,301.0,335.0,3.54,3.570,14.60,1.0,1.0,5.0,8.0
31,Volvo 142E,21.4,4.0,121.0,109.0,4.11,2.780,18.60,1.0,1.0,4.0,2.0

# Filling Method7

In [46]:
from sklearn.impute import KNNImputer
impute = KNNImputer()
df7 = df.drop(['model'],axis=1)
df7 = pd.DataFrame(impute.fit_transform(df7), columns = df7.columns)
print(df7)

     mpg  cyl   disp     hp  drat     wt   qsec   vs   am  gear  carb
0   21.0  6.0  160.0  110.0  3.90  2.620  16.46  0.0  1.0   4.0   4.0
1   21.0  6.0  160.0  110.0  3.90  2.875  17.02  0.0  1.0   4.0   4.0
2   22.8  4.0  108.0   93.0  3.85  2.320  18.61  1.0  1.0   4.0   1.0
3   21.4  6.0  258.0  110.0  3.08  3.215  19.44  1.0  0.0   3.0   1.0
4   18.7  8.0  360.0  175.0  3.15  3.440  17.02  0.0  0.0   3.0   2.0
5   18.1  6.0  225.0  105.0  2.76  3.460  20.22  1.0  0.0   3.0   1.0
6   14.3  8.0  360.0  245.0  3.21  3.570  15.84  0.0  0.0   3.0   4.0
7   24.4  4.0  146.7   62.0  3.69  3.190  20.00  1.0  0.0   4.0   2.0
8   22.8  4.0  140.8   95.0  3.92  3.150  22.90  1.0  0.0   4.0   2.0
9   19.2  6.0  167.6  123.0  3.92  3.440  18.30  1.0  0.0   4.0   4.0
10  17.8  6.0  167.6  123.0  3.92  3.440  18.90  1.0  0.0   4.0   4.0
11  16.4  8.0  275.8  180.0  3.07  4.070  17.40  0.0  0.0   3.0   3.0
12  17.3  8.0  275.8  180.0  3.07  3.730  17.60  0.0  0.0   3.0   3.0
13  15.2  8.0  275.8  180.0  3.07  3.780  18.00  0.0  0.0   3.0   3.0
14  10.4  8.0  472.0  205.0  2.93  5.250  17.98  0.0  0.0   3.0   4.0
15  10.4  8.0  460.0  215.0  3.00  5.424  17.82  0.0  0.0   3.0   4.0
16  14.7  8.0  440.0  230.0  3.23  5.345  17.42  0.0  0.0   3.0   4.0
17  32.4  4.0   78.7   66.0  4.08  2.200  19.47  1.0  1.0   4.0   1.0
18  30.4  4.0   75.7   52.0  4.93  1.615  18.52  1.0  1.0   4.0   2.0
19  33.9  4.0   71.1   65.0  4.22  1.835  19.90  1.0  1.0   4.0   1.0
20  21.5  4.0  120.1   97.0  3.70  2.465  20.01  1.0  0.0   3.0   1.0
21  15.5  8.0  318.0  150.0  2.76  3.520  16.87  0.0  0.0   3.0   2.0
22  15.2  8.0  304.0  150.0  3.15  3.435  17.30  0.0  0.0   3.0   2.0
23  13.3  8.0  350.0  245.0  3.73  3.840  15.41  0.0  0.0   3.0   4.0
24  19.2  8.0  400.0  175.0  3.08  3.845  17.05  0.0  0.0   3.0   2.0
25  27.3  4.0   79.0   66.0  4.08  1.935  18.90  1.0  1.0   4.0   1.0
26  26.0  4.0  120.3   91.0  4.43  2.140  16.70  0.0  1.0   5.0   2.0
27  30.4  4.0   95.1  113.0  3.77  1.513  16.90  1.0  1.0   5.0   2.0
28  15.8  8.0  351.0  264.0  4.22  3.170  14.50  0.0  1.0   5.0   4.0
29  19.7  6.0  145.0  175.0  3.62  2.770  15.50  0.0  1.0   5.0   6.0
30  15.0  8.0  301.0  335.0  3.54  3.570  14.60  0.0  1.0   5.0   8.0
31  21.4  4.0  121.0  109.0  4.11  2.780  18.60  1.0  1.0   4.0   2.0

# Filling Method8

In [48]:
from sklearn.impute import SimpleImputer
impute = SimpleImputer()
df8 = pd.DataFrame(impute.fit_transform(df7), columns = df7.columns)
df8

     mpg  cyl   disp     hp  drat     wt   qsec   vs   am  gear  carb
0   21.0  6.0  160.0  110.0  3.90  2.620  16.46  0.0  1.0   4.0   4.0
1   21.0  6.0  160.0  110.0  3.90  2.875  17.02  0.0  1.0   4.0   4.0
2   22.8  4.0  108.0   93.0  3.85  2.320  18.61  1.0  1.0   4.0   1.0
3   21.4  6.0  258.0  110.0  3.08  3.215  19.44  1.0  0.0   3.0   1.0
4   18.7  8.0  360.0  175.0  3.15  3.440  17.02  0.0  0.0   3.0   2.0
5   18.1  6.0  225.0  105.0  2.76  3.460  20.22  1.0  0.0   3.0   1.0
6   14.3  8.0  360.0  245.0  3.21  3.570  15.84  0.0  0.0   3.0   4.0
7   24.4  4.0  146.7   62.0  3.69  3.190  20.00  1.0  0.0   4.0   2.0
8   22.8  4.0  140.8   95.0  3.92  3.150  22.90  1.0  0.0   4.0   2.0
9   19.2  6.0  167.6  123.0  3.92  3.440  18.30  1.0  0.0   4.0   4.0
10  17.8  6.0  167.6  123.0  3.92  3.440  18.90  1.0  0.0   4.0   4.0
11  16.4  8.0  275.8  180.0  3.07  4.070  17.40  0.0  0.0   3.0   3.0
12  17.3  8.0  275.8  180.0  3.07  3.730  17.60  0.0  0.0   3.0   3.0
13  15.2  8.0  275.8  180.0  3.07  3.780  18.00  0.0  0.0   3.0   3.0
14  10.4  8.0  472.0  205.0  2.93  5.250  17.98  0.0  0.0   3.0   4.0
15  10.4  8.0  460.0  215.0  3.00  5.424  17.82  0.0  0.0   3.0   4.0
16  14.7  8.0  440.0  230.0  3.23  5.345  17.42  0.0  0.0   3.0   4.0
17  32.4  4.0   78.7   66.0  4.08  2.200  19.47  1.0  1.0   4.0   1.0
18  30.4  4.0   75.7   52.0  4.93  1.615  18.52  1.0  1.0   4.0   2.0
19  33.9  4.0   71.1   65.0  4.22  1.835  19.90  1.0  1.0   4.0   1.0
20  21.5  4.0  120.1   97.0  3.70  2.465  20.01  1.0  0.0   3.0   1.0
21  15.5  8.0  318.0  150.0  2.76  3.520  16.87  0.0  0.0   3.0   2.0
22  15.2  8.0  304.0  150.0  3.15  3.435  17.30  0.0  0.0   3.0   2.0
23  13.3  8.0  350.0  245.0  3.73  3.840  15.41  0.0  0.0   3.0   4.0
24  19.2  8.0  400.0  175.0  3.08  3.845  17.05  0.0  0.0   3.0   2.0
25  27.3  4.0   79.0   66.0  4.08  1.935  18.90  1.0  1.0   4.0   1.0
26  26.0  4.0  120.3   91.0  4.43  2.140  16.70  0.0  1.0   5.0   2.0
27  30.4  4.0   95.1  113.0  3.77  1.513  16.90  1.0  1.0   5.0   2.0
28  15.8  8.0  351.0  264.0  4.22  3.170  14.50  0.0  1.0   5.0   4.0
29  19.7  6.0  145.0  175.0  3.62  2.770  15.50  0.0  1.0   5.0   6.0
30  15.0  8.0  301.0  335.0  3.54  3.570  14.60  0.0  1.0   5.0   8.0
31  21.4  4.0  121.0  109.0  4.11  2.780  18.60  1.0  1.0   4.0   2.0

# Filling Method9

In [49]:
from sklearn.impute import MissingIndicator
impute = MissingIndicator()
df9 = pd.DataFrame(impute.fit_transform(df7))
df9

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]

# Filling Method10

In [50]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
impute = IterativeImputer()
df10 = pd.DataFrame(impute.fit_transform(df7), columns = df7.columns)
df10

     mpg  cyl   disp     hp  drat     wt   qsec   vs   am  gear  carb
0   21.0  6.0  160.0  110.0  3.90  2.620  16.46  0.0  1.0   4.0   4.0
1   21.0  6.0  160.0  110.0  3.90  2.875  17.02  0.0  1.0   4.0   4.0
2   22.8  4.0  108.0   93.0  3.85  2.320  18.61  1.0  1.0   4.0   1.0
3   21.4  6.0  258.0  110.0  3.08  3.215  19.44  1.0  0.0   3.0   1.0
4   18.7  8.0  360.0  175.0  3.15  3.440  17.02  0.0  0.0   3.0   2.0
5   18.1  6.0  225.0  105.0  2.76  3.460  20.22  1.0  0.0   3.0   1.0
6   14.3  8.0  360.0  245.0  3.21  3.570  15.84  0.0  0.0   3.0   4.0
7   24.4  4.0  146.7   62.0  3.69  3.190  20.00  1.0  0.0   4.0   2.0
8   22.8  4.0  140.8   95.0  3.92  3.150  22.90  1.0  0.0   4.0   2.0
9   19.2  6.0  167.6  123.0  3.92  3.440  18.30  1.0  0.0   4.0   4.0
10  17.8  6.0  167.6  123.0  3.92  3.440  18.90  1.0  0.0   4.0   4.0
11  16.4  8.0  275.8  180.0  3.07  4.070  17.40  0.0  0.0   3.0   3.0
12  17.3  8.0  275.8  180.0  3.07  3.730  17.60  0.0  0.0   3.0   3.0
13  15.2  8.0  275.8  180.0  3.07  3.780  18.00  0.0  0.0   3.0   3.0
14  10.4  8.0  472.0  205.0  2.93  5.250  17.98  0.0  0.0   3.0   4.0
15  10.4  8.0  460.0  215.0  3.00  5.424  17.82  0.0  0.0   3.0   4.0
16  14.7  8.0  440.0  230.0  3.23  5.345  17.42  0.0  0.0   3.0   4.0
17  32.4  4.0   78.7   66.0  4.08  2.200  19.47  1.0  1.0   4.0   1.0
18  30.4  4.0   75.7   52.0  4.93  1.615  18.52  1.0  1.0   4.0   2.0
19  33.9  4.0   71.1   65.0  4.22  1.835  19.90  1.0  1.0   4.0   1.0
20  21.5  4.0  120.1   97.0  3.70  2.465  20.01  1.0  0.0   3.0   1.0
21  15.5  8.0  318.0  150.0  2.76  3.520  16.87  0.0  0.0   3.0   2.0
22  15.2  8.0  304.0  150.0  3.15  3.435  17.30  0.0  0.0   3.0   2.0
23  13.3  8.0  350.0  245.0  3.73  3.840  15.41  0.0  0.0   3.0   4.0
24  19.2  8.0  400.0  175.0  3.08  3.845  17.05  0.0  0.0   3.0   2.0
25  27.3  4.0   79.0   66.0  4.08  1.935  18.90  1.0  1.0   4.0   1.0
26  26.0  4.0  120.3   91.0  4.43  2.140  16.70  0.0  1.0   5.0   2.0
27  30.4  4.0   95.1  113.0  3.77  1.513  16.90  1.0  1.0   5.0   2.0
28  15.8  8.0  351.0  264.0  4.22  3.170  14.50  0.0  1.0   5.0   4.0
29  19.7  6.0  145.0  175.0  3.62  2.770  15.50  0.0  1.0   5.0   6.0
30  15.0  8.0  301.0  335.0  3.54  3.570  14.60  0.0  1.0   5.0   8.0
31  21.4  4.0  121.0  109.0  4.11  2.780  18.60  1.0  1.0   4.0   2.0